# Generated by Django 4.1 on 2022-09-03 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basestory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='user',
        ),
        migrations.AddField(
            model_name='story',
            name='username',
            field=models.TextField(default=''),
        ),
    ]
