# Generated by Django 4.1 on 2022-08-31 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basestatus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='user',
        ),
    ]
