# Generated by Django 4.1 on 2022-09-02 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basestatus', '0003_note_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='user',
        ),
    ]
